### ISSUE TITLE
Changes to service vehicles

### ISSUE THREAD

**Issue by eMatt69** [Infixo/CS2-RealCity#2]
Would this mod allow changes to service vehicles, too? As is known, garbage collectors don't serve more and more big buildings in growing cities. Would be great if this mod could fix that.

**Comment by Infixo** [comment]
Try adding this to the Config.xml and you can put a bigger number than 20000 which is 20t.

```
<Prefab name="GarbageTruck01">
  <Component name="GarbageTruck">
	<Field name="m_GarbageCapacity" valueInt="20000" /> <!-- 20000 -->
  </Component>
</Prefab>
```

However, the issue with garbage is not rooted in truck size. It is much more complicated and related to the order in which the truck visits the buildings. If you increase the size it will help only partially.
